### ISSUE TITLE
Support old PHP versions

### ISSUE THREAD

**Issue by SmetDenis** [michal-kocarek/teamcity-messages#7]
Hi, 

Very nice tool, thanks!

Why did you set php version >=5.6 ?
I would like to use your package for our project, and we need to check code in php 5.4+...7.0 and hhvm via teamciy.
Is there some special features? I think you can change it to >=5.4 without any problems and check it on travis.

What do you think?

Thanks and best regards, Denis.

**Comment by michal-kocarek** [comment]
Hi Denis,
I have extended the compatiblity to PHP 5.5. Some variadic function arguments were replaced and it works fine.

If we replaced `finally` constructs inside MessageLogger, we should theoretically be able to enable it for PHP 5.4 as well...

**Comment by SmetDenis** [comment]
Hi @michal-kocarek,
Thanks!

> If we replaced finally constructs inside MessageLogger, we should theoretically be able to run it under PHP 5.4 as well...

is `try finally` really important condition for logger?

**Comment by michal-kocarek** [comment]
Denis, 
enjoy release [1.2.0](https://github.com/michal-kocarek/teamcity-messages/releases/tag/v1.2.0) with compatibility ranging from 5.4 to 7.0. Hope you find this library useful.
Happy Easter. Michal.

**Comment by SmetDenis** [comment]
Thats cool!  Thanks.
I will add it to my tool later https://github.com/JBZoo/TeamCity (docs coming soon)
